### ISSUE TITLE
Get error after login

### ISSUE THREAD

**Issue by snguyenc** [sunnygleason/chatengine-react-native-sample#1]
Hi, I just try to run the sample app on android, but I always get the error when login, 

console.error: {"error":{"config":{"transformRequest":{},"transformResponse":{},"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"method":"post","params":{"route":"bootstrap"},"url":"https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-4346b28e-89ad-11e8-94c4-4245bce006b6/chat-engine-server","data":"{\"uuid\":\"3c5cd6168c77f9aeed58780f2c6c5af5760fa87b\",\"global\":\"chat-engine\",\"authKey\":\"auth-key\"}"},"request":{"UNSENT":0,"OPENED":1,"HEADERS_RECEIVED":2,"LOADING":3,"DONE":4,"readyState":4,"status":404,"timeout":0,"withCredentials":true,"upload":{},"_aborted":false,"_hasError":false,"_method":"POST","_response":"","_url":"https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-4346b28e-89ad-11e8-94c4-4245bce006b6/chat-engine-server?route=bootstrap","_timedOut":false,"_trackingName":"unknown","_incrementalEvents":false,"responseHeaders":{"Connection":"keep-alive","Access-Control-Allow-Credentials":"true","Content-Length":"0","Content-Type":"text/plain; charset=utf-8","Date":"Tue, 17 Jul 2018 14:01:32 GMT"},"_requestId":null,"_headers":{"accept":"application/json, text/plain, */*","content-type":"application/json;charset=utf-8"},"_responseType":"","_sent":true,"_lowerCaseResponseHeaders":{"connection":"keep-alive","access-control-allow-credentials":"true","content-length":"0","content-type":"text/plain; charset=utf-8","date":"Tue, 17 Jul 2018 14:01:32 GMT"},"_subscriptions":[],"responseURL":"https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-4346b28e-89ad-11e8-94c4-4245bce006b6/chat-engine-server?route=bootstrap"},"response":{"data":"","status":404,"headers":{"connection":"keep-alive","access-control-allow-credentials":"true","content-length":"0","content-type":"text/plain; charset=utf-8","date":"Tue, 17 Jul 2018 14:01:32 GMT"},"config":{"transformRequest":{},"transformResponse":{},"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"method":"post","params":{"route":"bootstrap"},"url":"https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-4346b28e-89ad-11e8-94c4-4245bce006b6/chat-engine-server","data":"{\"uuid\":\"3c5cd6168c77f9aeed58780f2c6c5af5760fa87b\",\"global\":\"chat-engine\",\"authKey\":\"auth-key\"}"},"request":{"UNSENT":0,"OPENED":1,"HEADERS_RECEIVED":2,"LOADING":3,"DONE":4,"readyState":4,"status":404,"timeout":0,"withCredentials":true,"upload":{},"_aborted":false,"_hasError":false,"_method":"POST","_response":"","_url":"https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-4346b28e-89ad-11e8-94c4-4245bce006b6/chat-engine-server?route=bootstrap","_timedOut":false,"_trackingName":"unknown","_incrementalEvents":false,"responseHeaders":{"Connection":"keep-alive","Access-Control-Allow-Credentials":"true","Content-Length":"0","Content-Type":"text/plain; charset=utf-8","Date":"Tue, 17 Jul 2018 14:01:32 GMT"},"_requestId":null,"_headers":{"accept":"application/json, text/plain, */*","content-type":"application/json;charset=utf-8"},"_responseType":"","_sent":true,"_lowerCaseResponseHeaders":{"connection":"keep-alive","access-control-allow-credentials":"true","content-length":"0","content-type":"text/plain; charset=utf-8","date":"Tue, 17 Jul 2018 14:01:32 GMT"},"_subscriptions":[],"responseURL":"https://pubsub.pubnub.com/v1/blocks/sub-key/sub-c-4346b28e-89ad-11e8-94c4-4245bce006b6/chat-engine-server?route=bootstrap"}}}}
console.error
    YellowBox.js:71:10
RootEmitter.ChatEngine.throwError
    ce-core-chatengineprovider.js:30:5
<unknown>
    index.js:55:23
<unknown>
    moment.js:121:11
<unknown>
    
iterateeCallback
    
<unknown>
    
<unknown>
    
tryCallOne
    core.js:37:11

>>> Can you help review it?

**Comment by sunnygleason** [comment]
Hello, thank you for trying out the app! Sorry about the speed bump.

Usually this happens to me after the app has been idle for a couple weeks,
due to a timeout in the PubNub system.

Problem:

The ChatEngine FUNCTION gets turned off due to idle timeout after several days of inactivity. 

Potential Solution:

Log into the PubNub admin console, navigate to the ChatEngine App, go to the FUNCTIONs list for the app, then click on the ChatEngine function to make sure it's running.

If it's not running, click "start function" to get it running again.

If you reload the react native app, it should work again. Let me know if that doesn't work for you!

**Comment by sunnygleason** [comment]
Aha! I just looked back at the tutorial quickstart, it's missing this step:

* Configure a new ChatEngine application in PubNub [here](https://chat-engine-setup.pubnub.com)

This behavior will happen if the App was never set up to work with ChatEngine.

Hope that helps! -Sunny

**Comment by sunnygleason** [comment]
I'm pretty sure that was the issue. If the problem recurs, please feel free to re-open!

**Comment by trinadhkoya** [comment]
It was awesoem @sunnygleason , 
May i know how to do this for direct messaging (Private)
